from semantic_router import Route
from semantic_router.layer import RouteLayer
from semantic_router.encoders import OpenAIEncoder

import sys

# We use the table of contents of wolfSSL Documentation to create a Routes
wolfssl_doc = Route(
    name='wolfSSL',
    # Generated by ChatGPT from the table of contents of wolfSSL documentation.
    utterances = [
        "What is wolfSSL and its primary features?",
        "How do I build and install wolfSSL?",
        "Can you provide an introduction to getting started with wolfSSL?",
        "What are the key features of wolfSSL?",
        "How is wolfSSL adaptable to different platforms (portability)?",
        "How do I use callbacks in wolfSSL?",
        "What should I know about managing keys and certificates in wolfSSL?",
        "What are some debugging techniques for wolfSSL?",
        "Can you explain the library design of wolfSSL?",
        "How do I use wolfCrypt and what are its main functions?",
        "Can you guide me through a basic SSL tutorial using wolfSSL?",
        "What are the best practices when using wolfSSL in embedded devices?",
        "How compatible is wolfSSL with OpenSSL?",
        "What licensing options are available for wolfSSL?",
        "Where can I find support and consulting for wolfSSL?",
        "How do I stay updated with wolfSSL's latest changes?",
        "Where can I find the wolfSSL API reference?",
        "Where can I find the wolfCrypt API reference?",
        "What are the key API header files in wolfSSL?",
        "Can you provide an overview of SSL/TLS in the context of wolfSSL?",
        "What RFCs, specifications, and references are relevant to wolfSSL?",
        "How can I interpret and resolve error codes in wolfSSL?",
        "What are wolfSSL's capabilities regarding post-quantum cryptography?",
        "How can I port existing applications to use wolfSSL?"
    ]
)

# 日本語版のルートも作成
# これにより、日本語で質問が来たときにテンプレートやドキュメントの差し替えができる。
wolfssl_doc_ja = Route(
    name='wolfSSL-ja',
    utterances = [
        "wolfSSLを他のSSL/TLSライブラリと比較して、どのような利点がありますか？",
        "wolfSSLのテストスイートは、ライブラリの信頼性とセキュリティをどのように保証していますか？",
        "wolfSSLを使用してクライアントを実装する例を提供してもらえますか？",
        "wolfSSLサーバーを設定する例を見せてもらえますか？",
        "wolfSSLのEchoServerの例とは何ですか、またその動作方法は？",
        "wolfSSLのEchoClientの例はどのように実装されていますか？",
        "wolfSSLのパフォーマンスを評価するためのベンチマークはありますか？",
        "既存のクライアントアプリケーションをwolfSSLを使用するように変更するにはどうすればいいですか？",
        "サーバーアプリケーションをwolfSSLを利用するように変更するために必要な手順は何ですか？",
        "wolfSSLがサポートしているプロトコルは何ですか？",
        "wolfSSLがサポートしている暗号化方式は何ですか？",
        "wolfSSLはハードウェアアクセラレーションを利用した暗号化オプションを提供していますか？",
        "wolfSSLはSSLインスペクション（スニッファー）をどのように扱っていますか？",
        "wolfSSLの静的バッファ割り当てオプションとは何ですか？",
        "wolfSSLではデータ圧縮はどのように扱われますか？",
        "wolfSSLでは事前共有鍵はどのように使用されますか？",
        "wolfSSLがサポートするクライアント認証方法は何ですか？",
        "wolfSSLはサーバー名指示（SNI）をどのように実装していますか？",
        "wolfSSLでSSL/TLSハンドシェイクプロセスにどのような変更を加えることができますか？"
    ]
)

wolfmqtt_doc = Route(
    name='wolfMQTT', 
    utterances=[
        "What is the protocol overview of wolfMQTT?",
        "Which brokers are compatible with wolfMQTT?",
        "Does wolfMQTT support MQTT v3.1.1 specification?",
        "How does wolfMQTT support MQTT v5.0 specification?",
        "Is MQTT Sensor Network (MQTT-SN) supported by wolfMQTT?",
        "How can I get the source code of wolfMQTT?",
        "Can you provide instructions for building wolfMQTT on *nix/Mac?",
        "What are the steps to build wolfMQTT on Windows?",
        "How do I build wolfMQTT on Arduino?",
        "What is required to reformat wolfMQTT as a compatible Arduino Library?",
        "How can I include wolfMQTT in Arduino Libraries for Arduino version 1.8.2?",
        "What are the instructions for building wolfMQTT with MinGW?",
        "How can wolfMQTT be built in a non-standard environment?",
        "Can you explain cross compiling wolfMQTT?",
        "How to install wolfMQTT to a custom directory?",
        "What are the examples provided with wolfMQTT?",
        "Can you explain the client example in wolfMQTT?",
        "What is the simple standalone client example in wolfMQTT?",
        "How does the non-blocking client example in wolfMQTT work?",
        "What is the firmware example in wolfMQTT?",
        "How to use the Azure IoT Hub example in wolfMQTT?",
        "Can you explain the AWS IoT example in wolfMQTT?",
        "What is the Watson IoT example in wolfMQTT?",
        "How does the MQTT-SN example in wolfMQTT function?",
        "What is the multithread example in wolfMQTT?",
        "What options are available for examples in wolfMQTT?",
        "Can you describe the library design of wolfMQTT?",
        "What does the mqtt_client module in wolfMQTT do?",
        "How does the mqtt_packet module in wolfMQTT function?",
        "What is the purpose of the mqtt_socket module in wolfMQTT?",
        "Can you explain the example design in wolfMQTT?",
        "What can you tell me about the API reference for wolfMQTT?"
    ]
)

wolfmqtt_doc_ja = Route(
    name='wolfMQTT-ja', 
    utterances=[
        "wolfMQTTのプロトコル概要は何ですか？",
        "wolfMQTTと互換性のあるブローカーはどれですか？",
        "wolfMQTTはMQTT v3.1.1仕様をサポートしていますか？",
        "wolfMQTTはどのようにしてMQTT v5.0仕様をサポートしていますか？",
        "MQTTセンサーネットワーク（MQTT-SN）はwolfMQTTによってサポートされていますか？",
        "wolfMQTTのソースコードをどのように入手しますか？",
        "*nix/MacでwolfMQTTをビルドするための指示はありますか？",
        "Windows上でwolfMQTTをビルドする手順は何ですか？",
        "Arduino上でwolfMQTTをビルドするにはどうすればよいですか？",
        "wolfMQTTを互換性のあるArduinoライブラリとして再フォーマットするにはどうすればよいですか？",
        "Arduinoバージョン1.8.2用にwolfMQTTをArduinoライブラリに含めるにはどうすればよいですか？",
        "MinGWでwolfMQTTをビルドするための指示は何ですか？",
        "非標準環境でwolfMQTTをビルドするにはどうすればよいですか？",
        "wolfMQTTのクロスコンパイリングについて説明してください。",
        "カスタムディレクトリにwolfMQTTをインストールする方法は？",
        "wolfMQTTにはどのような例が提供されていますか？",
        "wolfMQTTのクライアント例について説明してください。",
        "wolfMQTTのシンプルなスタンドアロンクライアント例とは何ですか？",
        "wolfMQTTのノンブロッキングクライアント例はどのように機能しますか？",
        "wolfMQTTのファームウェア例とは何ですか？",
        "wolfMQTTでAzure IoT Hubの例を使用する方法は？",
        "wolfMQTTのAWS IoT例について説明してください。",
        "wolfMQTTのWatson IoT例とは何ですか？",
        "wolfMQTTのMQTT-SN例はどのように機能しますか？",
        "wolfMQTTのマルチスレッド例とは何ですか？",
        "wolfMQTTの例で利用可能なオプションは何ですか？",
        "wolfMQTTのライブラリ設計について説明してください。",
        "wolfMQTTのmqtt_clientモジュールは何をしますか？",
        "wolfMQTTのmqtt_packetモジュールはどのように機能しますか？",
        "wolfMQTTのmqtt_socketモジュールの目的は何ですか？",
        "wolfMQTTの例の設計を説明してください。",
        "wolfMQTTのAPIリファレンスについて何が言えますか？"
    ]
)


def get_router():
    """ Returns the router"""
    router = RouteLayer.from_json('route_layer.json')
    return router    

if __name__ == '__main__':
    if len(sys.argv) == 2 and sys.argv[1] == 'new':
        routes = [wolfssl_doc, wolfssl_doc_ja, wolfmqtt_doc, wolfmqtt_doc_ja]
        encoder = OpenAIEncoder()
        router = RouteLayer(encoder=encoder, routes=routes)
        router.to_json('route_layer.json')
    else:
        router = RouteLayer.from_json('route_layer.json')
        user_query = input('input >')
        print(router(user_query).name)
